# fly.toml app configuration file generated for datingtragik on 2023-07-09T20:37:04-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingtragik"
primary_region = "dfw"

[build]
  image = "mrrodarte/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dnbgxcbbp"
  CloudinarySettings__ApiKey="569445763986213"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
